In [1]:
import numpy as np

## History of Numpy:
#### Banaya Kisne? 
- Travis Oliphant ne 2005 mein banaya.
- Kyun Banaya? Python ki built-in lists slow thi, aur scientific computing aur machine learning ke liye ek efficient tool chahiye tha.
- Kya Karta Hai? Ye multi-dimensional arrays aur mathematical operations ko fast banata hai.
#### NumPy Kyon Zaroori Hai?
- Normal Python lists slow hoti hain, NumPy C language ka use karke calculations fast karta hai.
Vectorized operations ki wajah se ek saath multiple calculations efficiently ho sakti hain.
- Machine Learning aur Data Science mein ye backbone ka kaam karta hai.
#### NumPy Ke Main Features
- ndarray (NumPy Array): Ye ek fast aur memory-efficient array hota hai jo normal Python lists se behtar perform karta hai.
- Broadcasting: Ek chhoti value ko automatically bada karke operations ko optimize kar sakta hai.
- Mathematical Functions: Addition, subtraction, multiplication, logarithms, trigonometry, etc.
- Linear Algebra: Matrices ka multiplication, inverse, eigenvalues nikalna, etc.
- Random Number Generation: Machine Learning ke liye random numbers generate karna.
- Indexing & Slicing: Array ke andar se efficiently values ko filter karna.
- Integration with ML Libraries: TensorFlow, Scikit-learn, Pandas, etc. NumPy ke bina kaam nahi karte.
#### NumPy Ka Use Kahan Hota Hai?
- Machine Learning: Data manipulation, feature engineering, matrix operations.
- Data Science: Large datasets handle karna, fast computations.
- Computer Vision: Images ko array ki form mein store karna aur process karna.
- Finance: Stock market data ka analysis.
- Physics & Engineering: Simulations aur numerical computations.

### What is numpy ?
- NumPy ek Python library hai jo numerical computing ke liye banayi gayi hai. Matlab, agar tumhe bade datasets ke saath tez aur efficient calculations karni hoon, toh NumPy kaam aata hai. Matlab, ye normal Python lists se zyada fast aur powerful hai.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences :

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arraysrrays.

## Creating numpy arrays :

In [1]:
import numpy as np


In [12]:
"""
because of numpy is homogenius array so it only store one type of data at a time. If you give three types of data like int, float, string then it would 
check that what data type is huge then numpy convert it huge data type. Here string is huge data type so numpy convert all the values into string.
"""
# it is vector or 1D array :
arr = np.array([1,2,3,4,5, 'm', 'majid' , 3.3])
print(type(arr), arr)

<class 'numpy.ndarray'> ['1' '2' '3' '4' '5' 'm' 'majid' '3.3']


In [14]:
# This is one_d array we can also called it vector array but this is homogenius
one_d = np.array([1,2,3,4,5,6,7,8,9])
print(one_d)

[1 2 3 4 5 6 7 8 9]


In [13]:
# One_d array with arange: instead of writing obove we can also write in this form 

one_d_arr = np.arange(1,10)
print(one_d_arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
# Creating a 2D NumPy array (matrix) with shape (3, 4)  
array_2d = np.array([  
    [1, 2, 3, 4],  
    [5, 6, 7, 8],  
    [9, 10, 11, 12]  
])  

print("2D NumPy Array:")  
print(array_2d)

2D NumPy Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# I can use above code into like this short form of code:
a3 = np.arange(1,13).reshape(3,4)
print(a3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# create of 2D array we can call it matrix:  Because it is a homogenius array so it is in same form if we pass 4 value in one array its must passed 2nd array 4 values otherwise face an error
two_d = np.array([[12,11,4.3, 'majid'],[22,43, 5.3,'amir']])
print(two_d)

[['12' '11' '4.3' 'majid']
 ['22' '43' '5.3' 'amir']]


In [4]:
# creating of 3D array :
three_D = np.array([
    [[33,32,33],[32,11,22]]
    ,[[87,54,43], [24, 53, 23]]
])
print(three_D)

[[[33 32 33]
  [32 11 22]]

 [[87 54 43]
  [24 53 23]]]


In [10]:
# like above code
arr_3d = np.arange(1,13).reshape(2,2,3)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
# Creating a 3D NumPy array with shape (2, 3, 4)  
array_3d = np.array([  
    [[1, 2, 3, 4],  
     [5, 6, 7, 8],  
     [9, 10, 11, 12]],  

    [[13, 14, 15, 16],  
     [17, 18, 19, 20],  
     [21, 22, 23, 24]]  
])  

print("3D NumPy Array:")  
print(array_3d)

3D NumPy Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
import numpy as np
Three_d = np.arange(1,37).reshape(3,3,4)
Three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

## Passing value with different data types :

In [2]:
# We can pass the value with different data types by using of dtype :
diff_data = np.array([3,2,45,22], dtype = np.dtype(float))
print(diff_data)

[ 3.  2. 45. 22.]


In [3]:
# We can pass the value with different data types by using of dtype :
diff_data = np.array([3,2,45,22], dtype = np.dtype(complex))
print(diff_data)

[ 3.+0.j  2.+0.j 45.+0.j 22.+0.j]


In [5]:
# We can pass the value with different data types by using of dtype :
diff_data = np.array([3,2,45,22], dtype = np.dtype(bool))
print(diff_data)

[ True  True  True  True]


## arange function :

In [6]:
# It is like of range python built in function
data = np.arange(1, 11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
# it is also like of range function with separating by 2 mean every second value
data = np.arange(1, 11,2)
print(data)

[1 3 5 7 9]


In [16]:
""" 
reshape function in np: It means by using of arange function then we reshape the value into dimentional array
Ess mein ye hoga keh jitna ap ke pass value hogi oss hisab sy ap ko reshape dena pare ga otherwise itwillgive
you an error. like agr hamare pass (1,11) it means we only pass 2,5 or 5,2 otherwise it will say you nothave
which value you had pass. arange function and reshape used with another and separatly according to code situation
"""
data = np.arange(1,31).reshape(2,5,3)
print(data)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]


In [26]:
data = np.arange(1, 11).reshape(5,2)
print(data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [19]:
# np.ones and np.zeros we can pass all values in this form : passed by ones or zeros in tuple form it is like reshape function
data = np.ones((3,3))
print("this is ones matrix")
print(data)

print()
print("this is zeroes matrix")
data1 =  np.zeros((4,4))
print(data1, sep = '/')

print()
data2 = np.ones(5)
print('this is one d ones\n',data2)

this is ones matrix
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

this is zeroes matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

this is one d ones
 [1. 1. 1. 1. 1.]


In [8]:
# this could practice by self from datacamp chapter. This is python code with built in module enumerate
t = [ 'a', 'a' , 'b' , 'a']
e = enumerate(t , start = 1)
v = list(e)
for s in v:
    print(s)

(1, 'a')
(2, 'a')
(3, 'b')
(4, 'a')


In [22]:
# Generate a 2D array of shape (2, 3) with random values between 0 and 1  
""" 
by using of random function it means according to your given value it create bydefault random value 
it has Three usage like. 
here np.random.rand() first random is class and second rand is a method
1. random.rand(2,3) it means it will give you an two rows and three columns and according to given value it wil reslut
   in between 0 and 1 .
2. random.randint(2,5) it means np.random.randint(2, 5) generates a random integer that can be 2, 3, or 4.
   Each call results in a new random integer within this specified range. syntax (low, high) first is includive
   and secend is exclusive
3. random.randn(2,4) it is like rand which is first create value randomly in which positive and negative both have.
"""
random_array = np.random.rand(1,5,2)
print(random_array)
print(random_array.shape)


random_randInt = np.random.randint(0,4)
print(random_randInt)

random_randn = np.random.randn(2,3)
print(random_randn)

[[[0.41032738 0.29090193]
  [0.3014981  0.79351145]
  [0.16617018 0.12975735]
  [0.6547898  0.79030295]
  [0.56375886 0.8207961 ]]]
(1, 5, 2)
1
[[-1.89042513 -0.76419666 -0.85923744]
 [-1.14631088  0.77132018  0.84210257]]


In [6]:
# Ek random integer 1 aur 10 ke beech (10 excluded)
print(np.random.randint(1, 10))  

# 1D array of 5 random integers (1 to 100)
print(np.random.randint(1, 100, 5))  

# 2D array of shape (3,3) with numbers between 50 and 100
print(np.random.randint(50, 100, (3, 3)))  


4
[57 84 94 28 71]
[[87 89 60]
 [72 78 63]
 [90 86 82]]


In [26]:
# Ek random number between 0 and 1
print(f"{np.random.rand():.2f}")  

# 1D array of 5 random numbers
print(np.random.rand(5))  

# 2D array of shape (3,3)
print(np.random.rand(3, 3))  


0.42
[0.75285138 0.1752867  0.22389892 0.26745204 0.64319985]
[[0.079611   0.19677124 0.90539861]
 [0.89670262 0.19960035 0.05713025]
 [0.88308535 0.43302008 0.29745577]]


In [9]:
# Generate 5 evenly spaced values between 0 and 1  
"""
by using of linspace it means first vlaue is [1]start value , [2] end value , [3] num , number you want to print 
between them but output value with same difference.
Linespace bydefualt in float we can change any data type by using of dtype
"""
linspace_array = np.linspace(-3, 3, 5 , dtype = np.dtype(int))   # you can convert it in any dtype you want
print(linspace_array)

[-3 -2  0  1  3]


In [12]:
# Create a 4x4 identity matrix  
"""
an identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere.
"""
identity_matrix = np.identity(3)  
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array attributes :

In [27]:
a1 = np.arange(12)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(16).reshape(2,2,2,2)

In [28]:
print("This result of a1")
print(a1)
print()
print("This result of a2")
print(a2)
print()
print("This result of a3")
print(a3)

This result of a1
[ 0  1  2  3  4  5  6  7  8  9 10 11]

This result of a2
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

This result of a3
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [58]:
# ndim
# It will tell you that how much dimentional array in your code 
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
4


In [59]:
# shape : This tell how much number of items in every dimentional 
print(a1.shape)
print(a2.shape)
print(a3.shape)

(12,)
(3, 4)
(2, 2, 2, 2)


In [9]:
# size : This will tell us that in your given code how much elements are :
print(a1.size)
print(a2.size)
print(a3.size)



12
12
16


In [61]:
# itemsize : This will tell us that how much memory accupied your code
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [57]:
# dtype : This tell us that which data type you used and how much memory accopied
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## Indexing and slicing :

In [8]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [9]:
# indexing and slicing on 1D array
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
print(a1[5])
print(a1[ : 5])
print(a1[4 : ])
print(a1[-1 : -6 : -2])
print(a1[-6 : -1 ])


5
[0 1 2 3 4]
[ 4  5  6  7  8  9 10 11]
[11  9  7]
[ 6  7  8  9 10]


In [11]:
# indexing and slicing on 2D array :
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [36]:
# In matrix and tensor we only access of items by using of rows and columns
# ex:
print(a2[1,3])

7.0


In [12]:
# [row, column] wise access items
data = np.array(a2[2,2] ,dtype = int)
data1 = np.array(a2[1,2], dtype = int)
print(data)
print(data1)
print(a2[1,2] )      #This will by default output in float but we can change in integer or boolean like above code

10
6
6.0


In [7]:
a2[1,2]

6.0

In [13]:
# slicing and indexing on 3D array :
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
print(a3[1, 1,1])
print(a3[0, 1,1])
print(a3[1, 0 ,1])

7
3
5


In [33]:
print(a3[1,0,1])

5


In [25]:
# slicing on 2D array 
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
# scling with rows and colums
print(a2[:, 3])
print(a2[1,:])
print(np.array(a2[2,3], dtype = bool))

[ 3.  7. 11.]
[4. 5. 6. 7.]
True


## changing datatype :

In [21]:
"""
It is also used for checking that the data is right memory data type or not so we can change it according to datatype like if my age in float
so this would take huge memory and not sense that age in float so i can convert it into integer by using of astype function

"""
# I can change any data type by using of astype 
# suppose if i give age of any person by default it takes 64 bits and other memory is waste because age not take 64 bits so by using of astype i can save many memory
a3.astype(np.int32)
print(a3)
print(a3.itemsize)
print(a3.size)
print(a3.shape)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
4
8
(2, 2, 2)


## Array Operation :

In [44]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [41]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [43]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [23]:
# scaler operations :
# Arithematic operations :
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [24]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [25]:
a1-2


array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [26]:
a1+4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
a1**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]], dtype=int32)

## Relational Operations :

In [9]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# All of these relational operations answer would be in boolean form

a2 > 17

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
a2 < 21

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [34]:
a2[a2 <= 22]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [34]:
a2 <= 12

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [51]:
a2[a2 == 18].size

1

In [18]:
a2[a2 != 16].size

11

## Array Functions :

In [21]:
# Here outage np.round it means it will convert into nearest values not float like 23.2323
a1 = np.round(np.random.random((3,3))*100)
a1 = np.round(a1)                  # this will give an float like 12. just not like 12.3434343
a1

array([[89., 94., 62.],
       [59., 34., 24.],
       [40., 42., 63.]])

In [55]:
# min/max/sum/prod:

# It will tell us the minimum number from the given data
np.min(a1)

14.0

In [19]:
# Answer between 0,1 like random.rand
np.random.random((3,2))

array([[0.88256168, 0.22108886],
       [0.65334053, 0.34980495],
       [0.04174803, 0.40946851]])

In [56]:
# It will tell us the maximum number from the given data
np.max(a1)

95.0

In [22]:
# Here is on column wise sum of all colum you can also sum of rows by using axis = 1

np.sum(a1, axis = 0)

array([188., 170., 149.])

In [23]:
"""
But if i want to print row by row minimum and maximum then i can do this 
  0 ---> col, 1 ---->row for axis
 it will give us on every row minimum number 
"""

np.min(a1, axis = 1)

array([62., 24., 40.])

In [24]:
# like above maximum on column
np.max(a1 , axis= 0)

array([89., 94., 63.])

## mean/ median/ standard deviation/ variance :

In [64]:
a1

array([[22., 56., 15.],
       [ 8., 65., 90.],
       [89., 38., 28.]])

In [63]:
# Here are also find row wize and column wise these operations

np.mean(a1, axis = 1)

array([31.        , 54.33333333, 51.66666667])

In [60]:
np.median(a1)

38.0

In [61]:
np.std(a1)

29.086079144497972

In [62]:
np.var(a1)

846.0

## Dot Product :

In [13]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12, 24).reshape(4,3)
print(a2)
print("\n This is different(4*3)\n",a3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 This is different(4*3)
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [69]:
# This will automatically generate and  give an answer . Multiply by rows to column. Mean first matrix rows and second matrix column
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [27]:
m_2 = np.arange(4).reshape(2,2)
m_3 = np.arange(4,8).reshape(2,2)
print(m_2)
print("\n", m_3)
prod = np.dot(m_2, m_3)
prod

[[0 1]
 [2 3]]

 [[4 5]
 [6 7]]


array([[ 6,  7],
       [26, 31]])

## logarithm and exponential functions :

In [73]:
a1

array([[22., 56., 15.],
       [ 8., 65., 90.],
       [89., 38., 28.]])

In [70]:
np.log(a1)

array([[3.09104245, 4.02535169, 2.7080502 ],
       [2.07944154, 4.17438727, 4.49980967],
       [4.48863637, 3.63758616, 3.33220451]])

In [72]:
np.exp(a1)

array([[3.58491285e+09, 2.09165950e+24, 3.26901737e+06],
       [2.98095799e+03, 1.69488924e+28, 1.22040329e+39],
       [4.48961282e+38, 3.18559318e+16, 1.44625706e+12]])

## round/ ceil/ floor :

In [5]:
# round function give the value nearest to that value not float dot above values:
a4 = np.round(np.random.rand(2,3)*100)
print(a4)

[[97. 16. 67.]
 [14. 78. 19.]]


In [85]:
# ceil function give above to that value if i have 3.5 it will give 4.
a4 = np.ceil(np.random.rand(2,5)*40)
print(a4)

[[ 9. 17. 29. 15. 25.]
 [21. 40. 27.  7. 31.]]


In [34]:
# floor function give less value to original value like if i have 2.5 it will give 2. 
a4= np.floor(np.random.rand(3,5)*50)
print(a4)

[[19. 13. 19. 33. 34.]
 [37. 41. 19. 23. 41.]
 [21. 41. 19.  9. 10.]]


## slicing by fetching of fancy indexing



In [35]:
a4

array([[19., 13., 19., 33., 34.],
       [37., 41., 19., 23., 41.],
       [21., 41., 19.,  9., 10.]])

In [36]:
# by fetching just one value between them
print(np.array(a4[1,-1] , dtype = np.dtype(int)))

41


In [37]:
print(np.array(a4[-1, -3], dtype = bool))

True


In [38]:
print(a4[::2, 1::2])

[[13. 33.]
 [41.  9.]]


In [7]:
# Here is first row filtered and second column filtered
# and here last 2 like ::2 it means first starting to end but space of 2 and last 2::2 it means start column from 2 up work but space of 2 
a4[::2, 2::2]

array([[31., 27.],
       [ 3.,  7.]])

In [39]:
# first row with slicing and second column with slicing
# Here fetch value just from 1 row which is second
a4[1, 3:]

array([23., 41.])

In [40]:
# Fetching value from center.
a4[:2, 1:4]

array([[13., 19., 33.],
       [41., 19., 23.]])

In [41]:
# Here is first row by slicing and second column with slicing
a4[1:, 2:5]

array([[19., 23., 41.],
       [19.,  9., 10.]])

In [13]:
a4[0:2, 0:2 ]

array([[ 0., 29.],
       [ 9., 14.]])

In [14]:
# this is also known as fancy indexing

a4[::2, ::4]

array([[ 0., 18.],
       [29.,  2.]])

## slicing with 3D array :

In [22]:
np.random.seed(42)
a1 = np.random.randint(0,27, (3,3,3))
a1.sort()
a1

array([[[ 6, 14, 19],
        [ 7, 10, 20],
        [ 6, 18, 25]],

       [[10, 10, 22],
        [ 3, 20, 23],
        [ 2,  7, 23]],

       [[ 1, 20, 21],
        [ 5, 11, 23],
        [ 0,  1, 20]]])

In [17]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [118]:

a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [107]:
# by fetching of second value :
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [108]:
# by fetching of 3rd value
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [110]:
# by getting of 1st 2d array second row
a3[0,1,:]

array([3, 4, 5])

In [111]:
a3[1, :, 1:2]

array([[10],
       [13],
       [16]])

## Iterating 

In [42]:
"""
In this numpy library loop has three types
1. for i in a2:
2. for i in np.nditer(a2)
3. for i in a2:
        for row in i:

this is the three method apply on 2-D array and upto 
"""
a1 = np.arange(12)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(2,2,3)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [131]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [45]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [133]:
# It is also used for looping individual on matrix 
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [134]:
# this method is also used for looping individual on matrix
for i in a2:
    for row in i:
        print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [139]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [140]:
# this method apply on 3_D array 
for i in a3:
    for row in i:
        for element in row:
            print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [141]:
# this nditer is also apply on 3-D array but this is efficient and clean understandable code
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping :

In [142]:
"""
Transpose : This is used to transpose rows to columns and columns to rows 
It means it change rows to column and columns to rows.
It has two methods 
"""
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
# 1st method of transpose:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [144]:
# 2nd method of transpose:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [145]:
"""
Ravel: This is also used for converting of 2d and 3D and upto so on dinmentional array into one_D array answer in one row not like nditer in colums ans
"""
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
# This is second method but main purpose to convert all dimentional array into one-D 
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking :
- Horizental
- Vertical 

In [15]:
# Horizontal has two methods to stacking values 
a5 = np.arange(12).reshape(4,3)
a6 = np.arange(12, 24).reshape(4,3)
a5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
a6

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [16]:
# it is using to stacking or adding values into rows wize: it is used when we collect data from different platform or many other resources

np.hstack((a5, a6, a6 , a5))

array([[ 0,  1,  2, 12, 13, 14, 12, 13, 14,  0,  1,  2],
       [ 3,  4,  5, 15, 16, 17, 15, 16, 17,  3,  4,  5],
       [ 6,  7,  8, 18, 19, 20, 18, 19, 20,  6,  7,  8],
       [ 9, 10, 11, 21, 22, 23, 21, 22, 23,  9, 10, 11]])

In [20]:
np.hstack((a5,a6))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

## Vertical Stacking :

In [38]:
# vstack method is using to stacking or adding values into coulmns wise : it is used when we collect same type data into different places
np.vstack((a5, a6, a5, a6))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## Spliting :
- horizental
- vertical

In [41]:
a4


array([[17., 31., 32., 13., 35.],
       [16., 31., 13., 16.,  5.],
       [25., 11., 42., 27., 13.]])

In [40]:
a5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
# We just split any data into equal parts 
np.vsplit(a4, 3)

[array([[17., 31., 32., 13., 35.]]),
 array([[16., 31., 13., 16.,  5.]]),
 array([[25., 11., 42., 27., 13.]])]

In [168]:
np.hsplit(a4, 5)

[array([[ 3.],
        [24.],
        [35.]]),
 array([[43.],
        [44.],
        [25.]]),
 array([[46.],
        [48.],
        [17.]]),
 array([[ 8.],
        [47.],
        [10.]]),
 array([[ 7.],
        [25.],
        [ 3.]])]

In [3]:
rng = np.random.default_rng(42)   # modern Generator
x = rng.normal(size=(3, 3))
x

array([[ 0.30471708, -1.03998411,  0.7504512 ],
       [ 0.94056472, -1.95103519, -1.30217951],
       [ 0.1278404 , -0.31624259, -0.01680116]])

In [14]:
import datetime 
today = datetime.datetime.today()
print(today)

2025-08-29 22:52:45.202875
